name = "ChargeSimulationMethod"
uuid = "ba1e40c6-b836-43d2-9530-2500f7e26dce"
version = "0.1.0"
authors = ["Lucas Sales Barbosa <lucassalesb10@gmail.com>"]

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"

[compat]
LinearAlgebra = "1.12.0"
StaticArrays = "1.9.20"
